// © 2026 Andrii Shelenhivskyi. Licensed under Creative Commons Attribution-NonCommercial 4.0.

#pragma once

#include "NativeGameplayTags.h"

namespace ExeRunGameplayTags
{
	// === Input Cache tags ===

	EXERUN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputCache_LastAffirmativeMoveInput);
	EXERUN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputCache_MoveInputIntent);
	EXERUN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputCache_MoveInputVelocity);

	/*// === Extended Mover tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mover_IsWalkGroundSpeedModeActive);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mover_IsJogGroundSpeedModeActive);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mover_IsRunGroundSpeedModeActive);

	// === Movement tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Moving);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Falling);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_InAir);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_NavWalking);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_OnGround);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Crouching);

	// Movement Modes tags
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Mode_Walking);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Mode_Jogging);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Mode_Running);

	// === Roles tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Prisoner);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Guard);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Medic);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_NPC);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Player);

	// === Schedule events tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Bedtime);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_RollCall);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Meal);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Shower);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Alert);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_CheckedIn);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Wanted);

	// === Other Status tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_InForbiddenZone);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Fainted);*/
}